### ISSUE TITLE
Map update loop missed its desired rate of 10.0000Hz...

### ISSUE THREAD

**Issue by terencenwz** [ignc-research/arena-rosnav#46]
Hi I'm getting this warning while running the default code from noetic-devel branch.

python scripts/training/train_agent.py --agent MLP_ARENA2D

Example warnings:
[ WARN] [1647671519.840101736, 92308.850000000]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1800 seconds
[ WARN] [1647671519.849543441, 92309.060000000]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1900 seconds
[ WARN] [1647671519.866806290, 92309.400000000]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.2300 seconds

 My CPU and GPU usage remains very low. Any idea how to avoid this if I still want to maintain 10hz?

**Comment by Ducanor** [comment]
This warning can be ignored
